# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QColor, QPalette
from PyQt5.QtWidgets import QMessageBox


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(542, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Calculator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1 = QtWidgets.QPushButton(Calculator)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Calculator)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 2, 1, 1)
        self.pushButton_point = QtWidgets.QPushButton(Calculator)
        self.pushButton_point.setObjectName("pushButton_point")
        self.gridLayout.addWidget(self.pushButton_point, 5, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Calculator)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Calculator)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(Calculator)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Calculator)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(Calculator)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_minus.setStyleSheet("background-color : gray")
        self.gridLayout.addWidget(self.pushButton_minus, 4, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Calculator)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_multi = QtWidgets.QPushButton(Calculator)
        self.pushButton_multi.setObjectName("pushButton_multi")
        self.pushButton_multi.setStyleSheet("background-color : gray")
        self.gridLayout.addWidget(self.pushButton_multi, 3, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Calculator)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 1, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(Calculator)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_plus.setStyleSheet("background-color : gray")
        self.gridLayout.addWidget(self.pushButton_plus, 5, 3, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(Calculator)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 5, 0, 1, 1)
        self.pushButton_divide = QtWidgets.QPushButton(Calculator)
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_divide.setStyleSheet("background-color : gray")
        self.gridLayout.addWidget(self.pushButton_divide, 2, 3, 1, 1)
        self.pushButton_equal = QtWidgets.QPushButton(Calculator)
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_equal.setStyleSheet("background-color : green")
        self.gridLayout.addWidget(self.pushButton_equal, 6, 0, 1, 4)
        self.pushButton_C = QtWidgets.QPushButton(Calculator)
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_C.setStyleSheet("background-color : firebrick")
        self.gridLayout.addWidget(self.pushButton_C, 5, 2, 1, 1)
        self.user_edit = QtWidgets.QLineEdit(Calculator)
        self.user_edit.setText("")
        self.user_edit.setObjectName("user_edit")
        self.gridLayout.addWidget(self.user_edit, 1, 0, 1, 4)
        self.pushButton_6 = QtWidgets.QPushButton(Calculator)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 2, 1, 1)
        self.result = QtWidgets.QLabel(Calculator)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

        self.pushButton_point.clicked.connect(partial(self.push_button, self.pushButton_point.text()))
        self.pushButton_minus.clicked.connect(partial(self.push_button, self.pushButton_minus.text()))
        self.pushButton_plus.clicked.connect(partial(self.push_button, self.pushButton_plus.text()))
        self.pushButton_divide.clicked.connect(partial(self.push_button, self.pushButton_divide.text()))
        self.pushButton_multi.clicked.connect(partial(self.push_button, self.pushButton_multi.text()))
        self.pushButton_C.clicked.connect(partial(self.push_button, self.pushButton_C.text()))
        self.pushButton_equal.clicked.connect(partial(self.push_button, self.pushButton_equal.text()))
        self.pushButton_0.clicked.connect(partial(self.push_button, self.pushButton_0.text()))
        self.pushButton_1.clicked.connect(partial(self.push_button, self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(partial(self.push_button, self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(partial(self.push_button, self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(partial(self.push_button, self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(partial(self.push_button, self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(partial(self.push_button, self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(partial(self.push_button, self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(partial(self.push_button, self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(partial(self.push_button, self.pushButton_9.text()))

    def push_button(self, text):

        if text == 'C':
            self.user_edit.setText('')
        elif text == '=':
            try:
                result = eval(self.user_edit.text())
                self.result.setText(f"{self.user_edit.text()} = {float(result)}")
                self.user_edit.setText(f'{result}')
            except ZeroDivisionError as e:
                msg = QMessageBox()
                msg.setWindowTitle("Error")
                msg.setText(f"Zero Division Error: You can't divide by 0")
                msg.setIcon(QMessageBox.Critical)
                msg.setStandardButtons(QMessageBox.Ok)
                x = msg.exec_()
            except SyntaxError as e:
                msg = QMessageBox()
                msg.setWindowTitle("Error")
                msg.setText(f"Syntax Error! Check you expression")
                msg.setIcon(QMessageBox.Critical)
                msg.setStandardButtons(QMessageBox.Ok)
                x = msg.exec_()
            except Exception as e:
                msg = QMessageBox()
                msg.setWindowTitle("Error")
                msg.setText(f"Something went wrong!")
                msg.setIcon(QMessageBox.Critical)
                msg.setStandardButtons(QMessageBox.Ok)
                x = msg.exec_()

        else:
            screen = self.user_edit.text()
            self.user_edit.setText(screen + text)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_point.setText(_translate("Calculator", "."))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_7.setText(_translate("Calculator", "7"))
        self.pushButton_9.setText(_translate("Calculator", "9"))
        self.pushButton_minus.setText(_translate("Calculator", "-"))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_multi.setText(_translate("Calculator", "*"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_plus.setText(_translate("Calculator", "+"))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_divide.setText(_translate("Calculator", "/"))
        self.pushButton_equal.setText(_translate("Calculator", "="))
        self.pushButton_C.setText(_translate("Calculator", "C"))
        self.pushButton_6.setText(_translate("Calculator", "6"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    app.setStyle("Fusion")

    dark_palette = QPalette()

    dark_palette.setColor(QPalette.Window, QColor(53, 53, 53))
    dark_palette.setColor(QPalette.WindowText, Qt.white)
    dark_palette.setColor(QPalette.Base, QColor(25, 25, 25))
    dark_palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    dark_palette.setColor(QPalette.ToolTipBase, Qt.white)
    dark_palette.setColor(QPalette.ToolTipText, Qt.white)
    dark_palette.setColor(QPalette.Text, Qt.white)
    dark_palette.setColor(QPalette.Button, QColor(53, 53, 53))
    dark_palette.setColor(QPalette.ButtonText, Qt.white)
    dark_palette.setColor(QPalette.BrightText, Qt.red)
    dark_palette.setColor(QPalette.Link, QColor(42, 130, 218))
    dark_palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
    dark_palette.setColor(QPalette.HighlightedText, Qt.black)

    app.setPalette(dark_palette)

    app.setStyleSheet("QToolTip { color: #ffffff; background-color: #2a82da; border: 1px solid white; }")

    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
